# Generated by Django 2.2.4 on 2019-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190822_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checklist_title',
            field=models.CharField(default='Untitled', max_length=32),
        ),
    ]
